version: '3.8'

services:
  db:
    image: postgres:16
    container_name: gym-db
    environment:
      POSTGRES_DB: gymdb
      POSTGRES_USER: gymuser
      POSTGRES_PASSWORD: gym123
    ports:
      - "5433:5432"
    volumes:
      - gym_postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: gym-backend
    ports:
      - "8100:8100"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gymdb
      SPRING_DATASOURCE_USERNAME: gymuser
      SPRING_DATASOURCE_PASSWORD: gym123
      SERVER_PORT: 8100
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: gym-frontend
    ports:
      - "3090:80"
    depends_on:
      - backend

volumes:
  gym_postgres_data:
